Repository ak-0283/Samnwadh, pull requests merged in 2025-02, with the labels that each got.

#4 Changed the style of Feature heading
  Frontend/style.css
Labels: JWOC, Medium

#8 Authentication page done
  Frontend/index.html
  Frontend/login.html
  Frontend/script.js
  Frontend/signup.html
  Frontend/style.css
Labels: JWOC, Hard

#15 toggle button added
  Frontend/index.html
  Frontend/toggle.css
  Frontend/toggle.js
Labels: JWOC, Hard

#16 techstack page added
  Frontend/index.html
  Frontend/tech-stack.css
  Frontend/techstack.html
Labels: JWOC, Medium

#20 Contact us page added
  Frontend/contact.html
  Frontend/index.html
Labels: JWOC, Medium

#14 Added logo in navbar
  Frontend/index.html
  Frontend/logo.png
  Frontend/style.css
Labels: JWOC, Medium

#24 toggle button fixed
  Frontend/index.html
Labels: JWOC, Easy

#28 feedback form implemented
  Frontend/feedback.css
  Frontend/feedback.html
  Frontend/feedback.js
  Frontend/index.html
Labels: JWOC, Medium

#31 footer alignment adjusted by wrapping
  Frontend/style.css
Labels: JWOC, Medium

#35 Added EmailJS to establish b/w email and conatct page
  Frontend/config.js
  Frontend/contact.html
  Frontend/contact.js
  Frontend/index.html
  Frontend/techstack.html
Labels: JWOC 2025, Medium

#39 Redirect
  Frontend/tech-stack.css
  Frontend/techstack.html
Labels: JWOC 2025, Easy, good issue

#41 Links added
  Frontend/index.html
Labels: JWOC 2025, Easy

#44 Added the required fields as well as a reset button
  Frontend/download.png
  Frontend/signup.css
  Frontend/signup.html
Labels: JWOC 2025, Hard

#46 Implement Search Bar Functionality for Notess Website
  Frontend/script.js
  Frontend/tech-stack.css
  Frontend/techstack.html
Labels: JWOC 2025, Hard

#47 Add Navbar and Footer to the Tech Stack Page with Responsiveness
  Frontend/tech-stack.css
  Frontend/techstack.html
  Frontend/toggle.css
  Frontend/toggle.js
Labels: JWOC 2025, Hard

#49 Made the contact form responsive for smaller screens
  Frontend/contact.css
  Frontend/contact.html
Labels: JWOC 2025, Medium

#48 Add Navbar and Footer to the Contributor Page with Responsiveness
  Frontend/contributor/contributor.css
  Frontend/contributor/contributor.html
Labels: JWOC 2025, Hard

#62 Improve Scrollbar Styling for Better User Experience
  Frontend/style.css
Labels: JWOC 2025, Medium

#63 fixed the mobile responsiveness of the footer
  Frontend/contributor/contributor.html
  Frontend/style.css
  Frontend/toggle.css
Labels: JWOC 2025, Hard

#68 Removed the heading colour of the contributor page
  Frontend/contributor/contributor.css
Labels: JWOC 2025, Medium

#72 Added Animation
  Frontend/contributor/contributor.html
  Frontend/faq.html
  Frontend/index.html
  Frontend/techstack.html
Labels: JWOC 2025, Hard

#83 search filter added
  Frontend/faq.html
Labels: JWOC 2025, Medium

#94 Fixed the contributor page
  Frontend/contributor/contributor.css
  Frontend/contributor/contributor.html
Labels: JWOC 2025, Hard

#105 Removed the bg color of heading
  Frontend/tech-stack.css
Labels: JWOC 2025, Hard

#107 Fixed image compression
  Frontend/tech-stack.css
Labels: JWOC 2025, Medium

#115 Fixed the date of the signup page in smaller screens
  Frontend/signup.css
  Frontend/signup.html
Labels: JWOC 2025, Hard

#103 subcribe to Newsletter feature done
  Frontend/card.css
  Frontend/card.js
  Frontend/faq.html
  Frontend/feedback.css
  Frontend/index.html
  Frontend/login.html
  Frontend/logo.webp
  Frontend/privacy.html
  Frontend/style.css
Labels: JWOC 2025, Medium

#97 Feedback page button position fixed.
  Frontend/index.html
Labels: JWOC 2025, Medium

#84 Review section added
  Frontend/index.html
  Frontend/review.html
Labels: JWOC 2025, Medium

#85 Logo added
  Frontend/index.html
  Frontend/logo.png
  Frontend/review.html
  Frontend/style.css
Labels: JWOC 2025, Medium

#100 Logout feature done
  Frontend/index.html
Labels: JWOC 2025, Medium

#129 Fixed the alignment of about page
  Frontend/about.css
  Frontend/about.html
Labels: JWOC 2025, Medium

#130 Fixed Icon bug
  Frontend/contributor/contributor.html
  Frontend/privacy.html
  Frontend/review.html
  Frontend/techstack.html
Labels: JWOC 2025, Hard

#141 Modify blog page
  Frontend/blog.css
  Frontend/blog.html
Labels: JWOC 2025, Medium

#95 terms and conditions page added with navbar and footer
  Frontend/index.html
  Frontend/terms.html
Labels: JWOC 2025, Medium

#137 password matching done in signup page
  Frontend/script.js
Labels: JWOC 2025, Hard

#140 Reset button functionality added
  Frontend/script.js
  Frontend/signup.html
Labels: JWOC 2025, Medium

#145 Made the faq page responsive
  Frontend/faq.css
Labels: JWOC 2025, Hard

#124 Added navbar and footer for the faq page
  Frontend/contributor/contributor.html
  Frontend/faq.css
  Frontend/faq.html
Labels: JWOC 2025, Hard

#123 Fixed the feedback route in the contribute pge
  Frontend/contributor/contributor.html
Labels: JWOC 2025, Medium

#146 Removed the duplicates
  Frontend/index.html
Labels: JWOC 2025, Medium

#149 Made Ui changes to Contact Form
  Frontend/contact.css
  Frontend/contact.html
Labels: JWOC 2025, Hard

#125 added feedback in the home page
  Frontend/homefeedback.css
Labels: JWOC 2025, Hard

#127 Favicon Added
  Frontend/android-chrome-192x192.png
  Frontend/android-chrome-512x512.png
  Frontend/apple-touch-icon.png
  Frontend/createRoom.css
  Frontend/createRoom.html
  Frontend/createRoom.js
  Frontend/favicon-16x16.png
  Frontend/favicon-32x32.png
  Frontend/favicon.ico
  Frontend/index.html
  Frontend/site.webmanifest
  Frontend/style.css
Labels: JWOC 2025, Hard

#144 added dark mode feature
  Frontend/contributor/contributor.css
  Frontend/contributor/contributor.html
  Frontend/index.html
  Frontend/script.js
  Frontend/style.css
  Frontend/tech-stack.css
  Frontend/techstack.html
  Frontend/toggle.css
Labels: JWOC 2025

#185 Fixed the alignment and responsiveness of faq page
  Frontend/faq.css
  Frontend/faq.html
  Frontend/index.html
  Frontend/style.css
Labels: JWOC 2025

#206 Created the community page
  Frontend/community.css
  Frontend/community.html
  Frontend/index.html
  Frontend/jane.jpg
  Frontend/jen.jpg
  Frontend/joe.jpg
Labels: JWOC 2025

#188 scroll top button added techStack page
  Frontend/tech-stack.css
  Frontend/techstack.html
Labels: JWOC 2025, Medium

#214 Added a responsive footer to the about page
  Frontend/about.css
  Frontend/about.html
Labels: JWOC 2025, Hard

#217 Signup page toggle eye added
  Frontend/blog.html
  Frontend/signup.css
  Frontend/signup.html
Labels: JWOC 2025, Medium

#218 Login page toggle eye added
  Frontend/login.css
  Frontend/login.html
Labels: JWOC 2025, Easy

#221 Added navbar and footer to the feedback page
  Frontend/feedback.css
  Frontend/feedback.html
Labels: JWOC 2025, Hard

#191 alignment fixed
  Frontend/index.html
  Frontend/style.css
Labels: JWOC 2025, Hard

#192 Redirect Links in contribute fixed
  Frontend/contributor/contributor.html
Labels: JWOC 2025, Easy

#193 Footer Links added in the contribute
  Frontend/contributor/contributor.html
Labels: JWOC 2025

#229 Blog page scroll btn added
  Frontend/blog.css
  Frontend/blog.html
  Frontend/style.css
Labels: JWOC 2025, Easy

#228 Added a responsive footer to the community page
  Frontend/community.css
  Frontend/community.html
Labels: JWOC 2025, Hard

#250 Fixed the page,navbar,feedback and faq in dark mode
  Frontend/faq.css
  Frontend/index.html
  Frontend/style.css
Labels: JWOC 2025, Hard

#234 Changes the theme of login page
  Frontend/index.html
  Frontend/login.css
Labels: JWOC 2025, Hard

#240 Changes the theme of signup
  Frontend/signup.css
Labels: JWOC 2025, Medium

#241 Change the theme of feedback
  Frontend/feedback.css
Labels: JWOC 2025

#252 Added a responsive footer to the signup page
  Frontend/signup.css
  Frontend/signup.html
Labels: JWOC 2025, Hard

#256 Added a responsive footer to the login page
  Frontend/login.css
  Frontend/login.html
Labels: JWOC 2025, Hard

#251 added an error page (issue #230)
  Frontend/404.html
Labels: JWOC 2025, Hard

#271 Fixed Feedback overflow
  Frontend/feedback.css
Labels: JWOC 2025, Medium

#272 Updated about page
  Frontend/about.css
  Frontend/about.html
Labels: JWOC 2025, Medium

#232 no result found implemented in blog page
  Frontend/blog.html
Labels: JWOC 2025, Medium

#233 Blog page footer enhanced with proper redirection
  Frontend/blog.html
  Frontend/index.html
Labels: JWOC 2025, Hard

#235 Privacy page footer links enhanced.
  Frontend/privacy.html
Labels: JWOC 2025, Medium

#236 Terms page footer links added
  Frontend/terms.html
Labels: JWOC 2025, Medium

#239 Search bar added in main page faq section
  Frontend/index.html
Labels: JWOC 2025, Hard

#263 subscription,location link added in faq footer
  Frontend/faq.html
  Frontend/style.css
Labels: JWOC 2025, Hard

#274 Remove Padding
  Frontend/review.html
Labels: JWOC 2025, Medium

#276 Fixed Link of tech stack
  Frontend/techstack.html
Labels: JWOC 2025, Hard

#226 fixed redirect to community page from contribute page
  Frontend/contributor/contributor.html
  Frontend/index.html
Labels: JWOC 2025, Medium

#249 Dark mode in about page
  Frontend/about.css
  Frontend/about.html
  Frontend/blog.css
  Frontend/blog.html
  Frontend/toggle.js
Labels: JWOC 2025, Hard

#257 Added dark mode in login page
  Frontend/login.css
  Frontend/login.html
Labels: JWOC 2025, Hard

#283 Fixed overflow of login page
  Frontend/login.css
Labels: JWOC 2025, Hard

#284 Fixed Signup overflow
  Frontend/signup.css
Labels: JWOC 2025, Hard

#285 Fixed alignment of about us
  Frontend/about.css
Labels: JWOC 2025, Medium

#268 Blog Added
  Frontend/blog.html
  Frontend/index.html
Labels: JWOC 2025, Medium

#286 Fixed Arrow of Contact page
  Frontend/contact.css
Labels: JWOC 2025, Easy

#269 Added the darkmode in the terms and condition page
  Frontend/blog.html
  Frontend/terms.html
Labels: JWOC 2025, Medium

#270 Darkmode ui added to the terms container
  Frontend/privacy.html
  Frontend/terms.html
Labels: JWOC 2025, Hard

#207 Scroll top button added blog page
  Frontend/blog.html
Labels: JWOC 2025, Medium

#296 Darkmode added in the blog page
  Frontend/blog.html
Labels: JWOC 2025, Medium

#304 fixed links of the navbar in contributor page
  Frontend/contributor/contributor.html
Labels: JWOC 2025, Medium

#305 Fixed validation of input
  Frontend/contact.html
Labels: JWOC 2025, Hard

#306 Fixed design of login page
  Frontend/login.css
Labels: JWOC 2025, Hard

#313 Fixed footer bug
  Frontend/terms.html
Labels: JWOC 2025, Medium

#314 Fixed footer of faq and added copy right on index's footer
  Frontend/faq.html
  Frontend/index.html
Labels: JWOC 2025, Medium

#315 Fixed dark mode bug of review page
  Frontend/review.html
Labels: JWOC 2025, Hard

#316 Fixed Dark mode bug of about us
  Frontend/about.css
Labels: JWOC 2025, Hard

#307 footer links added in review page
  Frontend/review.html
Labels: JWOC 2025

#309 Terms page footer added
  Frontend/terms.html
Labels: JWOC 2025, Medium

#311 Contributor page search bar added with filter
  Frontend/contributor/contributor.html
Labels: JWOC 2025

#312 Contributor page footer enhanced
  Frontend/contributor/contributor.html
Labels: JWOC 2025, Medium
